name: Pull request opened process

on:
  workflow_call:

jobs:
  pull-request-opened:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: chTestORG

      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: chTestORG/org-issues
          path: config-repo
          token: ${{ steps.app-token.outputs.token }}

      - name: Check pull request base branch
        if: inputs.repo-type == 'front-end'
        uses: actions/github-script@v7
        env:
          script-name: "chek-pull-base-branch"
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/config-repo/projectV2/src/workflows/${{ env.script-name }}.mjs`;
            try {
              const { default: run } = await import(scriptPath);
              await run({ github, context, core });
            } catch (err) {
              core.setFailed(`Failed to execute ${scriptName}: ${err.message}`);
            }

      - name: Check linked issues on pull request body
        uses: actions/github-script@v7
        env:
          script-name: "chek-linked-issues-on-pull"
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/config-repo/projectV2/src/workflows/${{ env.script-name }}.mjs`;
            try {
              const { default: run } = await import(scriptPath);
              await run({ github, context, core });
            } catch (err) {
              core.setFailed(`Failed to execute ${scriptName}: ${err.message}`);
            }

      - name: Move issues on project board to Review
        uses: actions/github-script@v7
        env:
          script-name: "move-linked-issues-to-reviw"
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/config-repo/projectV2/src/workflows/${{ env.script-name }}.mjs`;
            try {
              const { default: run } = await import(scriptPath);
              await run({ github, context, core });
            } catch (err) {
              core.setFailed(`Failed to execute ${scriptName}: ${err.message}`);
            }
